import type { IceCreamType, TargetRanges } from './types'

// Target ranges from research/02-ideal-ranges-by-type.md
export const targetRanges: Record<IceCreamType, TargetRanges> = {
	cremeeis: {
		type: 'cremeeis',
		label: { de: 'Cremeeis', en: 'Cream Ice / Custard Gelato' },
		ts: { min: 38, max: 42 },
		fat: { min: 7, max: 10 },
		slng: { min: 7, max: 9 },
		sugar: { min: 16, max: 20 },
		pod: { min: 160, max: 200 },
		pac: { min: 240, max: 280 },
		overrun: { min: 25, max: 40 },
		servingTemp: { min: -13, max: -11 },
		protein: { min: 4, max: 6 },
	},
	milcheis: {
		type: 'milcheis',
		label: { de: 'Milcheis', en: 'Milk-Based Gelato' },
		ts: { min: 36, max: 40 },
		fat: { min: 4, max: 6 },
		slng: { min: 9, max: 12 },
		sugar: { min: 16, max: 20 },
		pod: { min: 160, max: 200 },
		pac: { min: 240, max: 280 },
		overrun: { min: 25, max: 40 },
		servingTemp: { min: -13, max: -11 },
		protein: { min: 3, max: 5 },
	},
	fruchtsorbet: {
		type: 'fruchtsorbet',
		label: { de: 'Fruchtsorbet', en: 'Fruit Sorbet' },
		ts: { min: 28, max: 34 },
		fat: { min: 0, max: 2 },
		slng: { min: 0, max: 0 },
		sugar: { min: 24, max: 32 },
		pod: { min: 220, max: 280 },
		pac: { min: 280, max: 340 },
		overrun: { min: 15, max: 30 },
		servingTemp: { min: -14, max: -12 },
		protein: { min: 0, max: 1 },
	},
	schokoladeneis: {
		type: 'schokoladeneis',
		label: { de: 'Schokoladeneis', en: 'Chocolate Gelato' },
		ts: { min: 38, max: 44 },
		fat: { min: 6, max: 10 },
		slng: { min: 7, max: 10 },
		sugar: { min: 16, max: 20 },
		pod: { min: 160, max: 200 },
		pac: { min: 230, max: 270 },
		overrun: { min: 25, max: 35 },
		servingTemp: { min: -13, max: -11 },
		protein: { min: 3, max: 5 },
	},
	nusseis: {
		type: 'nusseis',
		label: { de: 'Nusseis', en: 'Nut Gelato' },
		ts: { min: 40, max: 46 },
		fat: { min: 8, max: 12 },
		slng: { min: 7, max: 9 },
		sugar: { min: 14, max: 18 },
		pod: { min: 160, max: 180 },
		pac: { min: 240, max: 270 },
		overrun: { min: 25, max: 35 },
		servingTemp: { min: -13, max: -11 },
		protein: { min: 4, max: 6 },
	},
	joghurteis: {
		type: 'joghurteis',
		label: { de: 'Joghurteis', en: 'Yogurt Gelato' },
		ts: { min: 36, max: 40 },
		fat: { min: 4, max: 6 },
		slng: { min: 8, max: 11 },
		sugar: { min: 16, max: 20 },
		pod: { min: 160, max: 200 },
		pac: { min: 240, max: 280 },
		overrun: { min: 25, max: 40 },
		servingTemp: { min: -13, max: -11 },
		protein: { min: 3, max: 5 },
	},
}

export const iceCreamTypes: IceCreamType[] = Object.keys(targetRanges) as IceCreamType[]
